# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Api\:
        resource: '../src/Api/*'

    Api\Controller\:
        resource: '../src/Api/Controller'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/App/*'
        #        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    App\Command\WriteOffDictionaryCommand:
        arguments:
            - '@app.dictionary_service'
            - '@doctrine.orm.default_entity_manager'
        public: true
        tags: ['console.command']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.dictionary_service:
        class: 'App\Service\DictionaryService'
        arguments: ['%kernel.project_dir%']
        public: true

    app.word_service:
      class: 'App\Service\WordService'
      arguments: ['@doctrine.orm.default_entity_manager']
      public: true

    app.crossword_generator_service:
        class: 'App\Service\CrosswordGeneratorService'
        arguments: ['%kernel.project_dir%', '@doctrine.orm.default_entity_manager']
        public: true
